# Generated by Django 5.2.6 on 2025-10-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=100)),
                ('anio_inicio_clase', models.IntegerField()),
                ('anio_fin_clase', models.IntegerField()),
                ('maestro_clase', models.ForeignKey(limit_choices_to={'rol': 'maestro'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='Login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno_inscripcion', models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Login.usuario')),
                ('clase_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Gestion.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('valor_nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inscripcion_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='Gestion.inscripcion')),
            ],
        ),
    ]
