# Generated by Django 5.2.6 on 2025-10-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(blank=True, max_length=20, unique=True)),
                ('contrasena', models.CharField(max_length=128, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('rol', models.CharField(choices=[('alumno', 'Alumno'), ('maestro', 'Maestro'), ('admin', 'Administrador')], max_length=10)),
                ('anio_estudio', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Egresado', 'Egresado'), ('Expulsado', 'Expulsado')], default='Activo', max_length=10)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
