# Generated by Django 5.2.6 on 2025-09-30 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('apellido_alumno', models.CharField(max_length=100)),
                ('fecha_nacimiento_alumno', models.DateField()),
                ('anio_estudio_alumno', models.IntegerField()),
                ('genero_alumno', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=100)),
                ('anio_inicio_clase', models.IntegerField()),
                ('anio_fin_clase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id_maestro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_maestro', models.CharField(max_length=100)),
                ('apellido_maestro', models.CharField(max_length=100)),
                ('fecha_nacimiento_maestro', models.DateField(blank=True, null=True)),
                ('genero_maestro', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('especialidad_maestro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Login.alumno')),
                ('clase_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Login.clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='maestro_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='Login.maestro'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('valor_nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inscripcion_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='Login.inscripcion')),
            ],
        ),
    ]
