# Generated by Django 5.2.6 on 2025-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carnet_alumno',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contrasena_alumno',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='carnet_maestro',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='contrasena_maestro',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
