# Generated by Django 5.2.6 on 2025-10-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alumno_carnet_alumno_alumno_contrasena_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Egresado', 'Egresado'), ('Expulsado', 'Expulsado')], default='Activo', max_length=10),
        ),
    ]
